---
- name: copy a file
  hosts: all
  become: true
  tasks:
  - name: create a file
    file:
      path: /home/ansadmin/firstfile.txt
      state: touch
  - name: copy a file from one location to another location
    copy:
      src: /home/ansadmin/firstfile.txt
      dest: /etc
      mode: 0777
