---
- name: practice playbook
  hosts: all
  become: true
  tasks:
  - name: to install httpd package
    yum:
     name: httpd
     state: installed
  - name: to start service
    service: 
     name: httpd
     state: started
  - name: to install git 
    yum:
     name: git
     status: installed
    ignore_errors: yes 
