---
- name: install multiple users using loops
  hosts: all
  become: true
  tasks:
  - name: installmultiple users
    user: name='{{item}}' state=present
    with_items:
     - raj
     - tej
     - ram
     - saran
     - hem
